#Baseline #3

#Number of orders: 1
#Number of shipments per order: 1
#Challenges:
#  -Interruption: no
#  -Drop parts: no
#  -Sensor blackout: no
#  -Part flipping: yes
#  -Faulty parts: yes
#  -Moving obstacle: no
#Containers
# -Belt: no
# -Bins: yes
# -Shelf: yes
#AGV
# -order_0:
#   -shipment_0: agv2
#Time limit: Yes

time_limit: 500

options:
  gazebo_state_logging: true
  insert_models_over_bins: true
  insert_models_over_shelves: true
  belt_population_cycles: 0
  model_type_aliases:
    order_part1: pulley_part_red
    order_part2: disk_part_green
    order_part3: disk_part_blue
    order_part4: gear_part_blue
    order_part5: gasket_part_red
    order_part6: pulley_part_blue
    order_part7: gear_part_green
    order_part8: piston_rod_part_red

shelf_layout:
  row_1: ['base','collar',0,'base'] #shelves: 3, 4, 5
  row_2: ['pipe', 0,'base','base']   #shelves: 6, 7, 8
  row_3: ['base','pipe',0,'collar'] #shelves: 9, 10, 11


orders:
  order_0:
    announcement_condition: time
    announcement_condition_value: 0.0
    shipment_count: 1
    destinations: [agv2]
    products:
#      part_0:
#        type: pulley_part_red
#        pose:
#          xyz: [-0.12, -0.2, 0]
#          rpy: [0, 0, 0]
#      part_1:
#        type: pulley_part_red
#        pose:
#          xyz: [0.12, 0.2, 0]
#          rpy: ['pi', 0, 0]
      part_0:
        type: disk_part_green
        pose:
          xyz: [0.0, 0.0, 0]
          rpy: [0, 0, 0]
#      part_1:
#        type: disk_part_blue
#        pose:
#          xyz: [-0.15, 0.2, 0]
#          rpy: [0, 0, 0]
#      part_4:
#        type: disk_part_blue
#        pose:
#          xyz: [0.15, -0.2, 0]
#          rpy: [0, 0, 0]
#      part_2:
#        type: gear_part_blue
#        pose:
#          xyz: [-0.15, 0.2, 0]
#          rpy: [0, 0, 0]
      part_1:
        type: gasket_part_red
        pose:
          xyz: [ 0.0, 0.0, 0 ]
          rpy: [ 0, 0, '-pi/4' ]
#      part_4:
#        type: gear_part_green
#        pose:
#          xyz: [-0.12, -0.2, 0]
#          rpy: [0, 0, 0]
#      part_8:
#        type: piston_rod_part_red
#        pose:
#          xyz: [0.0, 0.0, 0]
#          rpy: [0, 0, '-pi/4']
#      part_5:
#        type: pulley_part_blue
#        pose:
#          xyz: [-0.15, 0.2, 0]
#          rpy: ['pi', 0, 0]





models_over_bins:
  bin13:
    models:
      disk_part_blue:
        xyz_start: [0.1, 0.1, 0.0]
        xyz_end: [0.5, 0.5, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 3
        num_models_y: 3
  bin16:
    models:
      disk_part_green:
        xyz_start: [0.1, 0.1, 0.0]
        xyz_end: [0.5, 0.5, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 3
        num_models_y: 3
  bin8:
    models:
      pulley_part_red:
        xyz_start: [0.15, 0.15, 0.0]
        xyz_end: [0.45, 0.45, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 2
        num_models_y: 1

  bin4:
    models:
      gear_part_blue:
        xyz_start: [0.1, 0.1, 0.0]
        xyz_end: [0.5, 0.5, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 3
        num_models_y: 3

  bin10:
    models:
      gasket_part_red:
        xyz_start: [ 0.1, 0.1, 0.0 ]
        xyz_end: [ 0.5, 0.5, 0.0 ]
        rpy: [ 0, 0, 'pi/4' ]
        num_models_x: 3
        num_models_y: 3

  bin1:
    models:
      pulley_part_blue:
        xyz_start: [0.15, 0.35, 0.0]
        xyz_end: [0.45, 0.45, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 2
        num_models_y: 1

  bin2:
    models:
      piston_rod_part_red:
        xyz_start: [0.15, 0.15, 0.0]
        xyz_end: [0.45, 0.45, 0.0]
        rpy: [0, 0, 'pi/4']
        num_models_x: 2
        num_models_y: 2

  bin3:
    models:
      gear_part_green:
        xyz_start: [0.15, 0.15, 0.0]
        xyz_end: [0.45, 0.45, 0.0]
        rpy: [0, 0, '-pi/2']
        num_models_x: 2
        num_models_y: 2

  bin5:
    models:
      pulley_part_blue:
        xyz_start: [0.15, 0.35, 0.0]
        xyz_end: [0.45, 0.45, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 2
        num_models_y: 1

  bin11:
    models:
      gear_part_green:
        xyz_start: [0.2, 0.1, 0.0]
        xyz_end: [0.4, 0.4, 0.0]
        rpy: [0, 0, '-pi/4']
        num_models_x: 2
        num_models_y: 2

#  bin12:
#    models:
#      disk_part_blue:
#        xyz_start: [0.28, 0.2, 0.0]
#        xyz_end: [0.28, 0.4, 0.0]
#        rpy: [0, 0, 0.28]
#        num_models_x: 1
#        num_models_y: 2




models_over_shelves:
  shelf5:
    models:
      pulley_part_red:
        xyz_start: [1, 0.4, 0.0]
        xyz_end: [0., 0.4, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 2
        num_models_y: 1

#Faulty products
faulty_products:
  - pulley_part_red_3
  - pulley_part_red_2
  - disk_part_blue_1
  - disk_part_blue_2
  - disk_part_green_3
  - disk_part_green_5
